services:
    rstudio:
        build:
            context: .
        environment:
            - TZ=Europe/Madrid
            - DISABLE_AUTH=true
            - PYTHONUSERBASE=/home/rstudio/.cache/pip
        volumes:
            - .:/home/rstudio/quarto-slides-example
            - cache:/home/rstudio/.cache
volumes:
  cache:
    external: true